### ISSUE TITLE
Fix timeouts delayed by IO blocking

### ISSUE THREAD

**Issue by tkannippoyil** [sharpstone/rack-timeout#30]
Timeout still happening in Heroku after using rack-timeout.
Using rack-timeout (0.0.4).
In config / initializers / timeout.rb 

> Rack::Timeout.timeout = 19 # seconds

**Comment by dentarg** [comment]
> Offering the option to just kill the entire process might be an alternative approach.

This was implemented in https://github.com/sharpstone/rack-timeout/pull/157

**Comment by schneems** [comment]
> This was implemented in #157

Hey, that was me!

> This might be unsolvable

I think this is true. Even when terminating the process it's still subject to it's own exit behavior. We don't have total control here. For example Puma could intercept the TERM and throw it away (it doesn't, but it could). I think this is a problem that rack-timeout cannot solve. We can perhaps make it better and provide options like #157 but it's up to the app developer to specify appropriate IO timeouts where Ruby code will be using native extensions or otherwise lose the ability to time itself out. I think that's the real answer. For example telling libpq that your session is limited to queries that take less than 30 seconds. 

It might be worth documenting how to set common cases of this if someone wants to send a doc PR.
